"use client";

import React, { useState, useEffect } from "react";
import { BarChart2, TrendingUp, DollarSign, Activity, Zap, Cpu, Network } from "lucide-react";

export default function AnalyticsPage() {
  const [workflows, setWorkflows] = useState<any[]>([]);
  const [pendingCount, setPendingCount] = useState(0);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [resW, resA] = await Promise.all([
          fetch("/api/workflows"),
          fetch("/api/approvals")
        ]);
        const dataW = await resW.json();
        const dataA = await resA.json();
        if (dataW.success) setWorkflows(dataW.workflows || []);
        if (dataA.success) setPendingCount(dataA.pendingApprovals?.length || 0);
      } catch (e) {}
    };
    fetchData();
    const interval = setInterval(fetchData, 5000);
    return () => clearInterval(interval);
  }, []);

  // Calculate dynamic stats on top of a realistic baseline for the demo
  const baseValue = 4200000;
  const liveValue = workflows.reduce((sum, w) => sum + (w.budgetSavings || (w.maxBudget * 0.15)), 0);
  const totalValue = baseValue + liveValue;

  const baseDecisions = 1402;
  const totalDecisions = baseDecisions + (workflows.length * 3);
  const humanInput = 142 + pendingCount;

  const baseCost = 12450;
  const totalCost = baseCost + (workflows.length * 8.8);

  const baseTime = 840;
  const totalTime = baseTime + (workflows.length * 4);

  // Dynamic Chart (Inject live workflows into the last month)
  const chartData = [60, 80, 45, 90, 75, 40, 85, 100, 65, 50, 70, Math.min(100, 95 + workflows.length)];

  // Dynamic Risk Distribution
  const total = workflows.length || 1;
  let lowCount = workflows.filter(w => w.riskScore < 30).length;
  let medCount = workflows.filter(w => w.riskScore >= 30 && w.riskScore <= 60).length;
  let highCount = workflows.filter(w => w.riskScore > 60).length;

  // Add baseline risk to prevent 0% rendering issues
  const lowRisk = Math.round(((lowCount + 75) / (total + 100)) * 100);
  const medRisk = Math.round(((medCount + 18) / (total + 100)) * 100);
  const highRisk = Math.round(((highCount + 7) / (total + 100)) * 100);

  return (
    <div className="animate-in fade-in duration-500 pb-10 h-[calc(100vh-6rem)] flex flex-col p-8 overflow-y-auto custom-scrollbar">
      <div className="flex items-center justify-between mb-8 shrink-0">
        <div className="flex items-center gap-5">
          <div className="p-3 rounded-xl bg-purple-500/10 border border-purple-500/20 relative">
            <BarChart2 size={32} className="text-purple-500 relative z-10" />
            <div className="absolute inset-0 bg-purple-500/20 blur-xl rounded-full" />
          </div>
          <div>
            <h1 className="text-3xl font-semibold tracking-tight text-white mb-1">OS Analytics & ROI</h1>
            <p className="text-slate-400 text-sm">Enterprise performance metrics and cost savings generated by autonomous agents.</p>
          </div>
        </div>
        <div className="px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-sm text-white font-medium flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
          Live Data Stream
        </div>
      </div>

      {/* Top Stats Row */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-6">
        <div className="glass-panel p-6 rounded-2xl border-emerald-500/30 bg-emerald-500/5 relative overflow-hidden group">
          <div className="absolute -right-4 -top-4 opacity-10 group-hover:opacity-20 transition-opacity">
            <TrendingUp size={100} className="text-emerald-500" />
          </div>
          <div className="flex items-center gap-3 mb-2">
            <div className="p-2 bg-emerald-500/20 rounded-lg text-emerald-400"><DollarSign size={20} /></div>
            <span className="text-slate-300 font-semibold text-sm uppercase tracking-wider">Total Value Created</span>
          </div>
          <div className="text-4xl font-bold text-white mb-1">₹{(totalValue / 1000000).toFixed(2)}M</div>
          <div className="text-emerald-400 text-xs font-bold">+12% vs last month</div>
        </div>

        <div className="glass-panel p-6 rounded-2xl relative overflow-hidden group">
          <div className="flex items-center gap-3 mb-2">
            <div className="p-2 bg-blue-500/20 rounded-lg text-blue-400"><Activity size={20} /></div>
            <span className="text-slate-300 font-semibold text-sm uppercase tracking-wider">Decisions Made</span>
          </div>
          <div className="text-4xl font-bold text-white mb-1">{totalDecisions.toLocaleString()}</div>
          <div className="text-blue-400 text-xs font-bold">{humanInput} requiring human input</div>
        </div>

        <div className="glass-panel p-6 rounded-2xl relative overflow-hidden group">
          <div className="flex items-center gap-3 mb-2">
            <div className="p-2 bg-purple-500/20 rounded-lg text-purple-400"><Cpu size={20} /></div>
            <span className="text-slate-300 font-semibold text-sm uppercase tracking-wider">Agent API Cost</span>
          </div>
          <div className="text-4xl font-bold text-white mb-1">₹{totalCost.toLocaleString(undefined, { maximumFractionDigits: 0 })}</div>
          <div className="text-slate-400 text-xs font-medium">Avg ₹8.8 per workflow</div>
        </div>

        <div className="glass-panel p-6 rounded-2xl relative overflow-hidden group">
          <div className="flex items-center gap-3 mb-2">
            <div className="p-2 bg-yellow-500/20 rounded-lg text-yellow-400"><Zap size={20} /></div>
            <span className="text-slate-300 font-semibold text-sm uppercase tracking-wider">Time Saved</span>
          </div>
          <div className="text-4xl font-bold text-white mb-1">{totalTime} hrs</div>
          <div className="text-slate-400 text-xs font-medium">Equivalent to 5 full-time heads</div>
        </div>
      </div>

      {/* Charts Row */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Agent Activity Bar Chart */}
        <div className="glass-panel p-6 rounded-2xl lg:col-span-2 flex flex-col relative overflow-hidden">
          {/* Background grid effect */}
          <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.02)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.02)_1px,transparent_1px)] bg-[size:20px_20px] pointer-events-none"></div>
          
          <h3 className="text-lg font-bold text-white mb-6 flex items-center gap-2 relative z-10">
            <Network size={20} className="text-blue-400" /> Multi-Agent Swarm Activity
          </h3>
          <div className="flex-1 flex items-end gap-2 h-48 mt-auto pt-10 relative z-10">
            {chartData.map((val, i) => (
              <div key={i} className="flex-1 flex flex-col items-center justify-end gap-2 group cursor-pointer h-full">
                <div 
                  className="w-full rounded-t-sm relative transition-all duration-1000 ease-out group-hover:scale-y-105" 
                  style={{ 
                    height: `${val}%`, 
                    backgroundColor: i === chartData.length - 1 ? 'rgba(16, 185, 129, 0.4)' : 'rgba(59, 130, 246, 0.2)',
                    boxShadow: i === chartData.length - 1 ? '0 0 20px rgba(16, 185, 129, 0.2)' : 'none',
                    borderTop: `1px solid ${i === chartData.length - 1 ? 'rgba(16, 185, 129, 1)' : 'rgba(59, 130, 246, 0.5)'}`
                  }}>
                  {/* Neon top cap */}
                  <div className={`absolute top-0 left-0 w-full h-1 ${i === chartData.length - 1 ? 'bg-emerald-400 animate-pulse' : 'bg-blue-400 opacity-50'}`}></div>
                  
                  <div className="absolute -top-8 left-1/2 -translate-x-1/2 opacity-0 group-hover:opacity-100 text-xs font-bold text-white bg-slate-800 px-2 py-1 rounded-md border border-slate-700 transition-opacity whitespace-nowrap z-20">
                    {val}k tokens
                  </div>
                </div>
                <span className={`text-[10px] font-bold uppercase ${i === chartData.length - 1 ? 'text-emerald-400' : 'text-slate-500'}`}>
                  {['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][i]}
                </span>
              </div>
            ))}
          </div>
        </div>

        {/* Risk Distribution */}
        <div className="glass-panel p-6 rounded-2xl flex flex-col">
          <h3 className="text-lg font-bold text-white mb-6">Workflow Risk Distribution</h3>
          <div className="flex-1 flex flex-col justify-center gap-6">
            <div className="flex flex-col gap-2">
              <div className="flex justify-between items-end">
                <span className="text-emerald-400 font-bold text-sm">Low Risk (Autonomous)</span>
                <span className="text-white font-bold">{lowRisk}%</span>
              </div>
              <div className="h-3 w-full bg-white/5 rounded-full overflow-hidden">
                <div className="h-full bg-emerald-500 rounded-full transition-all duration-1000" style={{ width: `${lowRisk}%` }}></div>
              </div>
            </div>
            
            <div className="flex flex-col gap-2">
              <div className="flex justify-between items-end">
                <span className="text-yellow-400 font-bold text-sm">Medium Risk (Monitored)</span>
                <span className="text-white font-bold">{medRisk}%</span>
              </div>
              <div className="h-3 w-full bg-white/5 rounded-full overflow-hidden">
                <div className="h-full bg-yellow-500 rounded-full transition-all duration-1000" style={{ width: `${medRisk}%` }}></div>
              </div>
            </div>

            <div className="flex flex-col gap-2">
              <div className="flex justify-between items-end">
                <span className="text-red-400 font-bold text-sm">High Risk (Human Required)</span>
                <span className="text-white font-bold">{highRisk}%</span>
              </div>
              <div className="h-3 w-full bg-white/5 rounded-full overflow-hidden">
                <div className="h-full bg-red-500 rounded-full transition-all duration-1000" style={{ width: `${highRisk}%` }}></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
