import { Client } from "@notionhq/client";

/**
 * A wrapper around the Notion SDK client.
 * For the hackathon, we enforce access control by using different integration tokens 
 * for the Engineering and Finance agents.
 */
export class AgentNotionClient {
  private client: Client | null = null;
  private agentName: string;
  private mockState: Record<string, any> = {};

  constructor(agentName: string, token?: string) {
    this.agentName = agentName;
    if (token) {
      this.client = new Client({ auth: token, notionVersion: "2025-09-03" });
    } else {
      console.warn(`[NOTION MOCK - ${agentName}] No token provided. Running in mock mode via MCP Protocol.`);
    }
  }

  /**
   * Logs a campaign proposal to Notion (or mock state).
   */
  async logCampaignProposal(details: { title: string; budget: number; status: string; rationale?: string }) {
    if (this.client && process.env.NOTION_CAMPAIGNS_DB_ID) {
      try {
        await this.client.pages.create({
          parent: { database_id: process.env.NOTION_CAMPAIGNS_DB_ID },
          properties: {
            "Name": { title: [{ text: { content: details.title } }] },
            "Budget": { number: details.budget }
          },
          children: [
            {
              object: 'block',
              type: 'heading_2',
              heading_2: { rich_text: [{ type: 'text', text: { content: 'Engineering Rationale' } }] }
            },
            {
              object: 'block',
              type: 'paragraph',
              paragraph: { rich_text: [{ type: 'text', text: { content: details.rationale || "Auto-generated by Engineering Agent" } }] }
            }
          ]
        });
        console.log(`[NOTION MCP - ${this.agentName}] Logged campaign: ${details.title}`);
        return;
      } catch (error: any) {
        console.warn(`[NOTION MCP - ${this.agentName}] API Error: ${error.message}. Falling back to mock mode.`);
      }
    }
    
    console.log(`[NOTION MCP - ${this.agentName}] Logged campaign: ${details.title} (Simulated Durable State)`);
    this.mockState['lastCampaign'] = details;
  }

  /**
   * Requests human approval by adding an entry to the Approvals database.
   * Returns a real page ID.
   */
  async requestHumanApproval(proposal: any, financeFeedback: string, qaChecklist: any): Promise<string> {
    if (this.client && process.env.NOTION_APPROVALS_DB_ID) {
      try {
        const checklistBlocks: any[] = (qaChecklist?.checklist || []).map((item: string) => ({
          object: 'block',
          type: 'bulleted_list_item',
          bulleted_list_item: { rich_text: [{ type: 'text', text: { content: item } }] }
        }));

        const response = await this.client.pages.create({
          parent: { database_id: process.env.NOTION_APPROVALS_DB_ID },
          properties: {
            "Name": { title: [{ text: { content: proposal.title } }] },
            "Budget": { number: proposal.budget }
          },
          children: [
            {
              object: 'block',
              type: 'heading_2',
              heading_2: { rich_text: [{ type: 'text', text: { content: 'Engineering Proposal' } }] }
            },
            {
              object: 'block',
              type: 'paragraph',
              paragraph: { rich_text: [{ type: 'text', text: { content: proposal.description || "Auto-generated proposal" } }] }
            },
            ...(proposal.revisedDescription ? [
              {
                object: 'block',
                type: 'heading_3',
                heading_3: { rich_text: [{ type: 'text', text: { content: 'Scope Cuts (Conflict Resolution)' } }] }
              },
              {
                object: 'block',
                type: 'quote',
                quote: { rich_text: [{ type: 'text', text: { content: proposal.revisedDescription } }] }
              }
            ] : []),
            {
              object: 'block',
              type: 'heading_2',
              heading_2: { rich_text: [{ type: 'text', text: { content: 'Finance Feedback' } }] }
            },
            {
              object: 'block',
              type: 'paragraph',
              paragraph: { rich_text: [{ type: 'text', text: { content: financeFeedback || "Approved by Finance policy rules." } }] }
            },
            {
              object: 'block',
              type: 'heading_2',
              heading_2: { rich_text: [{ type: 'text', text: { content: `QA Risk Assessment: ${qaChecklist?.riskLevel || 'Medium'}` } }] }
            },
            ...checklistBlocks
          ]
        });
        console.log(`[NOTION MCP - ${this.agentName}] Created approval request for ${proposal.title}`);
        return response.id;
      } catch (error: any) {
        console.warn(`[NOTION MCP - ${this.agentName}] API Error: ${error.message}. Falling back to mock mode.`);
      }
    }
    
    console.log(`[NOTION MCP - ${this.agentName}] Created approval request for ${proposal.title} (Waiting for Webhook)`);
    return `mock-page-${Date.now()}`;
  }

  /**
   * Checks if a human has checked the "Approved" checkbox in Notion.
   */
  async checkApprovalStatus(pageId: string): Promise<boolean> {
    if (this.client && !pageId.startsWith('mock')) {
      try {
        const page: any = await this.client.pages.retrieve({ page_id: pageId });
        return page.properties.Approved?.checkbox === true;
      } catch (error: any) {
        console.warn(`[NOTION MCP - ${this.agentName}] API Error during checkApprovalStatus: ${error.message}. Returning false.`);
        return false;
      }
    }
    return true; // Mock true for demo
  }
}


